server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # File posisi yang benar

client:
  url: http://loki:3100/api/prom/push # URL Loki yang benar

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/*log # Menyesuaikan path log untuk menangkap semua file log

